
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 06 19:48:28 CDT 2016
//----------------------------------------------------

package autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_NE = 5;
  public static final int SHORT = 20;
  public static final int CHAR = 19;
  public static final int EQUALS = 39;
  public static final int PERIOD = 40;
  public static final int PLUSOP = 47;
  public static final int MINUSOP = 48;
  public static final int OP_GT = 6;
  public static final int DOUBLE = 23;
  public static final int LPAREN = 35;
  public static final int PRIVATE = 26;
  public static final int INT = 17;
  public static final int TILDE = 12;
  public static final int RPAREN = 36;
  public static final int INSTANCEOF = 10;
  public static final int STATIC = 29;
  public static final int AND = 45;
  public static final int SEMICOLON = 42;
  public static final int ASTERICK = 46;
  public static final int OP_GE = 2;
  public static final int UNARY_DEC = 57;
  public static final int BANG = 52;
  public static final int COMMA = 43;
  public static final int CLASS = 14;
  public static final int RSLASH = 49;
  public static final int IF = 16;
  public static final int OP_LOR = 9;
  public static final int THIS = 31;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 28;
  public static final int SUPER = 30;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int OP_LT = 7;
  public static final int PERCENT = 50;
  public static final int PIPE = 44;
  public static final int HAT = 11;
  public static final int NULL = 25;
  public static final int VOID = 32;
  public static final int BYTE = 18;
  public static final int LITERAL = 54;
  public static final int COLON = 41;
  public static final int OP_LE = 3;
  public static final int LBRACE = 37;
  public static final int ELSE = 15;
  public static final int WHILE = 33;
  public static final int FLOAT = 22;
  public static final int PUBLIC = 27;
  public static final int RBRACE = 38;
  public static final int UNARY_INC = 56;
  public static final int OP_EQ = 4;
  public static final int LONG = 21;
  public static final int QUESTION = 51;
  public static final int ASS_ADD = 34;
  public static final int OP_LAND = 8;
  public static final int INTNUMBER = 55;
  public static final int IDENTIFIER = 53;
}

