
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 22 12:55:37 CST 2016
//----------------------------------------------------

package autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int times = 7;
  public static final int number = 2;
  public static final int minus = 4;
  public static final int negate = 8;
  public static final int EOF = 0;
  public static final int plus = 3;
  public static final int sum = 5;
  public static final int error = 1;
  public static final int rparen = 11;
  public static final int product = 6;
  public static final int lparen = 10;
  public static final int mean = 9;
}

