
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 22 17:20:08 CST 2016
//----------------------------------------------------

package autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int salad = 14;
  public static final int shrimp = 20;
  public static final int ELSE = 11;
  public static final int wonton = 13;
  public static final int INT = 27;
  public static final int PRIVATE = 22;
  public static final int IF = 10;
  public static final int PUBLIC = 23;
  public static final int eggdropsoup = 16;
  public static final int x = 2;
  public static final int OBJECT = 29;
  public static final int eggroll = 12;
  public static final int FLOAT = 28;
  public static final int PROTECTED = 24;
  public static final int EOF = 0;
  public static final int chicken = 21;
  public static final int rparen = 9;
  public static final int beef = 18;
  public static final int hotsoursoup = 15;
  public static final int error = 1;
  public static final int ABSTRACT = 30;
  public static final int PACKAGE = 25;
  public static final int NONABSTRACT = 31;
  public static final int e = 7;
  public static final int semi = 33;
  public static final int d = 6;
  public static final int noodlesoup = 17;
  public static final int lparen = 8;
  public static final int c = 5;
  public static final int VOID = 26;
  public static final int tofu = 19;
  public static final int b = 4;
  public static final int a = 3;
  public static final int name = 32;
}

