
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 15 16:30:23 CST 2016
//----------------------------------------------------

package autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 18;
  public static final int minus = 23;
  public static final int INT = 12;
  public static final int FI = 19;
  public static final int num = 21;
  public static final int IF = 17;
  public static final int y = 20;
  public static final int times = 24;
  public static final int x = 9;
  public static final int divide = 25;
  public static final int FLOAT = 13;
  public static final int EOF = 0;
  public static final int q = 16;
  public static final int id = 26;
  public static final int p = 15;
  public static final int o = 14;
  public static final int rparen = 8;
  public static final int error = 1;
  public static final int plus = 22;
  public static final int e = 6;
  public static final int d = 5;
  public static final int semi = 10;
  public static final int lparen = 7;
  public static final int c = 4;
  public static final int b = 3;
  public static final int a = 2;
  public static final int comma = 11;
}

